### PR TITLE
Fix base classes, consts and virtual destructors

### PR DESCRIPTION
**Pull request by jdcaporale**
Fixes missing virtual destructors and the const correctness of many of the robot base member functions. 
A good opportunity to do more minor clean up on the base classes, if anything comes to mind.

This may require some const-correctness fixes to existing code.

### CODE REVIEW

**Comment by jdcaporale** [comment]
Deals with #80

**Review by ShaneRozenLevy — APPROVED** [review]
Changes LGTM. What testing have you done?

**Comment by ShaneRozenLevy** [comment]
I suspect if we do have memory leaks they are minor since we are not creating and removing a ton of these objects.

**Comment by jdcaporale** [comment]
Tested and working on a quadrupedal robot, but not in the examples, best I can currently do.

**Pull request merged**
